export { default as Animal } from "./animal.svg";
export { default as Beauty } from "./beauty.svg";
export { default as Consulting } from "./consulting.svg";
export { default as Cook } from "./cook.svg";
export { default as Fashion } from "./fashion.svg";
export { default as Game } from "./game.svg";
export { default as Health } from "./health.svg";
export { default as Music } from "./music.svg";
export { default as Sports } from "./sports.svg";
